// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_name_ from "./routes/api/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $option1_cadastro from "./routes/option1/cadastro.tsx";
import * as $option1_estoque from "./routes/option1/estoque.tsx";
import * as $option1_historico from "./routes/option1/historico.tsx";
import * as $option1_index from "./routes/option1/index.tsx";
import * as $option1_protocolo from "./routes/option1/protocolo.tsx";
import * as $option10_cadastro from "./routes/option10/cadastro.tsx";
import * as $option10_estoque from "./routes/option10/estoque.tsx";
import * as $option10_index from "./routes/option10/index.tsx";
import * as $option11_cadastro from "./routes/option11/cadastro.tsx";
import * as $option11_estoque from "./routes/option11/estoque.tsx";
import * as $option11_index from "./routes/option11/index.tsx";
import * as $option12_cadastro from "./routes/option12/cadastro.tsx";
import * as $option12_estoque from "./routes/option12/estoque.tsx";
import * as $option12_index from "./routes/option12/index.tsx";
import * as $option2_cadastro from "./routes/option2/cadastro.tsx";
import * as $option2_estoque from "./routes/option2/estoque.tsx";
import * as $option2_historico from "./routes/option2/historico.tsx";
import * as $option2_index from "./routes/option2/index.tsx";
import * as $option2_protocolo from "./routes/option2/protocolo.tsx";
import * as $option3_cadastro from "./routes/option3/cadastro.tsx";
import * as $option3_estoque from "./routes/option3/estoque.tsx";
import * as $option3_historico from "./routes/option3/historico.tsx";
import * as $option3_index from "./routes/option3/index.tsx";
import * as $option3_protocolo from "./routes/option3/protocolo.tsx";
import * as $option4_cadastro from "./routes/option4/cadastro.tsx";
import * as $option4_estoque from "./routes/option4/estoque.tsx";
import * as $option4_historico from "./routes/option4/historico.tsx";
import * as $option4_index from "./routes/option4/index.tsx";
import * as $option4_protocolo from "./routes/option4/protocolo.tsx";
import * as $option5_cadastro from "./routes/option5/cadastro.tsx";
import * as $option5_estoque from "./routes/option5/estoque.tsx";
import * as $option5_historico from "./routes/option5/historico.tsx";
import * as $option5_index from "./routes/option5/index.tsx";
import * as $option5_protocolo from "./routes/option5/protocolo.tsx";
import * as $option6_cadastro from "./routes/option6/cadastro.tsx";
import * as $option6_estoque from "./routes/option6/estoque.tsx";
import * as $option6_historico from "./routes/option6/historico.tsx";
import * as $option6_index from "./routes/option6/index.tsx";
import * as $option6_protocolo from "./routes/option6/protocolo.tsx";
import * as $option7_cadastro from "./routes/option7/cadastro.tsx";
import * as $option7_estoque from "./routes/option7/estoque.tsx";
import * as $option7_historico from "./routes/option7/historico.tsx";
import * as $option7_index from "./routes/option7/index.tsx";
import * as $option7_protocolo from "./routes/option7/protocolo.tsx";
import * as $option8_cadastro from "./routes/option8/cadastro.tsx";
import * as $option8_estoque from "./routes/option8/estoque.tsx";
import * as $option8_historico from "./routes/option8/historico.tsx";
import * as $option8_index from "./routes/option8/index.tsx";
import * as $option8_protocolo from "./routes/option8/protocolo.tsx";
import * as $option9_cadastro from "./routes/option9/cadastro.tsx";
import * as $option9_estoque from "./routes/option9/estoque.tsx";
import * as $option9_index from "./routes/option9/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/[name].tsx": $api_name_,
    "./routes/index.tsx": $index,
    "./routes/option1/cadastro.tsx": $option1_cadastro,
    "./routes/option1/estoque.tsx": $option1_estoque,
    "./routes/option1/historico.tsx": $option1_historico,
    "./routes/option1/index.tsx": $option1_index,
    "./routes/option1/protocolo.tsx": $option1_protocolo,
    "./routes/option10/cadastro.tsx": $option10_cadastro,
    "./routes/option10/estoque.tsx": $option10_estoque,
    "./routes/option10/index.tsx": $option10_index,
    "./routes/option11/cadastro.tsx": $option11_cadastro,
    "./routes/option11/estoque.tsx": $option11_estoque,
    "./routes/option11/index.tsx": $option11_index,
    "./routes/option12/cadastro.tsx": $option12_cadastro,
    "./routes/option12/estoque.tsx": $option12_estoque,
    "./routes/option12/index.tsx": $option12_index,
    "./routes/option2/cadastro.tsx": $option2_cadastro,
    "./routes/option2/estoque.tsx": $option2_estoque,
    "./routes/option2/historico.tsx": $option2_historico,
    "./routes/option2/index.tsx": $option2_index,
    "./routes/option2/protocolo.tsx": $option2_protocolo,
    "./routes/option3/cadastro.tsx": $option3_cadastro,
    "./routes/option3/estoque.tsx": $option3_estoque,
    "./routes/option3/historico.tsx": $option3_historico,
    "./routes/option3/index.tsx": $option3_index,
    "./routes/option3/protocolo.tsx": $option3_protocolo,
    "./routes/option4/cadastro.tsx": $option4_cadastro,
    "./routes/option4/estoque.tsx": $option4_estoque,
    "./routes/option4/historico.tsx": $option4_historico,
    "./routes/option4/index.tsx": $option4_index,
    "./routes/option4/protocolo.tsx": $option4_protocolo,
    "./routes/option5/cadastro.tsx": $option5_cadastro,
    "./routes/option5/estoque.tsx": $option5_estoque,
    "./routes/option5/historico.tsx": $option5_historico,
    "./routes/option5/index.tsx": $option5_index,
    "./routes/option5/protocolo.tsx": $option5_protocolo,
    "./routes/option6/cadastro.tsx": $option6_cadastro,
    "./routes/option6/estoque.tsx": $option6_estoque,
    "./routes/option6/historico.tsx": $option6_historico,
    "./routes/option6/index.tsx": $option6_index,
    "./routes/option6/protocolo.tsx": $option6_protocolo,
    "./routes/option7/cadastro.tsx": $option7_cadastro,
    "./routes/option7/estoque.tsx": $option7_estoque,
    "./routes/option7/historico.tsx": $option7_historico,
    "./routes/option7/index.tsx": $option7_index,
    "./routes/option7/protocolo.tsx": $option7_protocolo,
    "./routes/option8/cadastro.tsx": $option8_cadastro,
    "./routes/option8/estoque.tsx": $option8_estoque,
    "./routes/option8/historico.tsx": $option8_historico,
    "./routes/option8/index.tsx": $option8_index,
    "./routes/option8/protocolo.tsx": $option8_protocolo,
    "./routes/option9/cadastro.tsx": $option9_cadastro,
    "./routes/option9/estoque.tsx": $option9_estoque,
    "./routes/option9/index.tsx": $option9_index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
